steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '--build-arg', 'VITE_API_URL=${_VITE_API_URL}',
         '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/control-panel-repo/frontend:latest',
         '.']
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/control-panel-repo/frontend:latest'
substitutions:
    _VITE_API_URL: 'https://backend-control-panel-589130197067.us-central1.run.app'
